---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lts-app
  namespace: default
spec:
  selector:
    matchLabels:
      lts: web
  template:
    metadata:
      labels:
        lts: web
        version: zero
    spec:
      containers:
        - name: lts-app
          image: jakekara/lts-app:latest
          imagePullPolicy: Always
          env:
            - name: LTS_AUTH_CODE
              value: "26950978009823473"
          # resources:
          #   limits:
          #     cpu: 250m
          #     memory: 512Mi
          #   requests:
          #     cpu: 150m
          #     memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/search?query=fear&start=0
              port: 7082
            timeoutSeconds: 5
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: lts-app
  namespace: default
spec:
  selector:
    lts: web
  ports:
    - port: 7082
      name: lts-app-port
      targetPort: 7082
